const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.TextBox,
		C3.Plugins.Touch,
		C3.Plugins.TiledBg,
		C3.Plugins.Mouse,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.bound,
		C3.Behaviors.wrap,
		C3.Plugins.Particles,
		C3.Plugins.Arr,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Flash,
		C3.Behaviors.EightDir,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Fade,
		C3.Plugins.NinePatch,
		C3.Plugins.List,
		C3.Plugins.PlatformInfo,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Acts.ScrollY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.List.Exps.ItemCount,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Arr.Acts.SetX,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.NinePatch.Acts.Destroy,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.List.Exps.ItemTextAt,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Plugins.Spritefont2.Exps.TextWidth,
		C3.Plugins.NinePatch.Acts.SetHeight,
		C3.Plugins.Spritefont2.Exps.TextHeight,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Touch.Cnds.OnHoldGestureObject,
		C3.Plugins.Sprite.Cnds.PickTopBottom,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursorSprite
	];
};
self.C3_JsPropNameTable = [
	{heigth: 0},
	{rotate: 0},
	{float: 0},
	{ZYE: 0},
	{NES_BOLD: 0},
	{Sólido: 0},
	{tiles: 0},
	{Teclado: 0},
	{EntradaDeTexto: 0},
	{Toque: 0},
	{HungerBar: 0},
	{HealthBar: 0},
	{HapinessBar: 0},
	{EnergyBar: 0},
	{teleport: 0},
	{secondaryValue: 0},
	{stringValue: 0},
	{button: 0},
	{cursor: 0},
	{Mouse: 0},
	{NESCASH: 0},
	{lastX: 0},
	{lastY: 0},
	{felicidade: 0},
	{nutricao: 0},
	{saudavel: 0},
	{ID: 0},
	{roupa: 0},
	{price: 0},
	{ArrastarSoltar: 0},
	{generic_sprites: 0},
	{RestritoAoLayout: 0},
	{scroll: 0},
	{speedY: 0},
	{thing: 0},
	{loop: 0},
	{DarAVolta: 0},
	{thing2: 0},
	{confete: 0},
	{SpeedY: 0},
	{Gravity: 0},
	{JumpStrength: 0},
	{MaxFallSpeed: 0},
	{Alive: 0},
	{flappy: 0},
	{minigame_log: 0},
	{log_base: 0},
	{InventarioLista: 0},
	{staticss: 0},
	{health: 0},
	{damage: 0},
	{MoverPara: 0},
	{Piscar: 0},
	{Senóide: 0},
	{cake: 0},
	{timer: 0},
	{timermax: 0},
	{dragging: 0},
	{"8Direções": 0},
	{gecko: 0},
	{gun: 0},
	{Projétil: 0},
	{DestruirForaDoLayout: 0},
	{bullet: 0},
	{gameover: 0},
	{Esmaecer: 0},
	{bullet2: 0},
	{hearths: 0},
	{hearths2: 0},
	{dialog: 0},
	{Lista: 0},
	{NES_BOLD2: 0},
	{ZYEClothes: 0},
	{cursor2: 0},
	{order: 0},
	{fogaobotao: 0},
	{Info: 0},
	{hearth: 0},
	{hunger: 0},
	{hapyness: 0},
	{energy: 0},
	{cash: 0},
	{minigamespeed: 0},
	{talk: 0},
	{timespath: 0},
	{first: 0},
	{second: 0},
	{third: 0}
];

self.InstanceType = {
	ZYE: class extends self.ISpriteInstance {},
	NES_BOLD: class extends self.ISpriteFontInstance {},
	tiles: class extends self.ITilemapInstance {},
	Teclado: class extends self.IInstance {},
	EntradaDeTexto: class extends self.ITextInputInstance {},
	Toque: class extends self.IInstance {},
	HungerBar: class extends self.ITiledBackgroundInstance {},
	HealthBar: class extends self.ITiledBackgroundInstance {},
	HapinessBar: class extends self.ITiledBackgroundInstance {},
	EnergyBar: class extends self.ITiledBackgroundInstance {},
	button: class extends self.ISpriteInstance {},
	cursor: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	NESCASH: class extends self.ISpriteFontInstance {},
	generic_sprites: class extends self.ISpriteInstance {},
	scroll: class extends self.ISpriteInstance {},
	thing: class extends self.ISpriteInstance {},
	loop: class extends self.ISpriteInstance {},
	thing2: class extends self.ISpriteInstance {},
	confete: class extends self.IParticlesInstance {},
	flappy: class extends self.ISpriteInstance {},
	minigame_log: class extends self.ISpriteInstance {},
	log_base: class extends self.ISpriteInstance {},
	InventarioLista: class extends self.IArrayInstance {},
	staticss: class extends self.ITiledBackgroundInstance {},
	cake: class extends self.ISpriteInstance {},
	gecko: class extends self.ISpriteInstance {},
	gun: class extends self.ISpriteInstance {},
	bullet: class extends self.ISpriteInstance {},
	gameover: class extends self.ISpriteInstance {},
	bullet2: class extends self.ISpriteInstance {},
	hearths: class extends self.ITiledBackgroundInstance {},
	hearths2: class extends self.ITiledBackgroundInstance {},
	dialog: class extends self.IWorldInstance {},
	Lista: class extends self.IListInstance {},
	NES_BOLD2: class extends self.ISpriteFontInstance {},
	ZYEClothes: class extends self.ISpriteInstance {},
	cursor2: class extends self.ISpriteInstance {},
	fogaobotao: class extends self.ISpriteInstance {},
	Info: class extends self.IInstance {},
	hearth: class extends self.IParticlesInstance {}
}